<a href="https://colab.research.google.com/github/GabsCavalcant/Aplicacao-Utilizando-llm-Rn-etc/blob/main/TransformandoDados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame(np.arange(36).reshape(6,6))

In [5]:
df

    0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35

In [10]:
df.drop([1,5],axis= 1 )

    0   2   3   4
0   0   2   3   4
1   6   8   9  10
2  12  14  15  16
3  18  20  21  22
4  24  26  27  28
5  30  32  33  34

In [15]:
serie = pd.Series(np.arange(6))
serie.name = 'Nova variavel'

serie

0    0
1    1
2    2
3    3
4    4
5    5
Name: Nova variavel, dtype: int64

In [17]:
df = df.join(serie)

In [26]:
df.sort_values(by='Nova variavel', ascending=False)

    0   1   2   3   4   5  Nova variavel
5  30  31  32  33  34  35              5
4  24  25  26  27  28  29              4
3  18  19  20  21  22  23              3
2  12  13  14  15  16  17              2
1   6   7   8   9  10  11              1
0   0   1   2   3   4   5              0